Rename the packages
Signed-off-by: Juerg Haefliger <juergh@proton.me>

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -3,27 +3,52 @@
 # Install tryboot files
 #
 
-dest_dir=${1:-}
+pkg_name=${1}
+dest_dir=debian/${pkg_name}
 
-etc_dir="${dest_dir}"/etc
-bin_dir="${dest_dir}"/usr/bin
-lib_dir="${dest_dir}"/usr/lib/rpi-tryboot
+case "${pkg_name}" in
 
-# Install scripts
-mkdir -p "${bin_dir}"
-cp bin/tryboot-* "${bin_dir}"/
+	rpi-tryboot-simple)
+		etc_dir="${dest_dir}"/etc
+		bin_dir="${dest_dir}"/usr/bin
+		lib_dir="${dest_dir}"/usr/lib/rpi-tryboot
 
-# Install helper library and hook scripts
-mkdir -p "${lib_dir}"
-cp bin/functions "${lib_dir}"/
+		# Install scripts
+		mkdir -p "${bin_dir}"
+		cp bin/tryboot-* "${bin_dir}"/
 
-# Install config files
-mkdir -p "${etc_dir}"/default/tryboot.d "${etc_dir}"/tryboot.d
-cp etc/tryboot "${etc_dir}"/default/
-cp etc/tryboot.d/* "${etc_dir}"/tryboot.d/
+		# Install helper library and hook scripts
+		mkdir -p "${lib_dir}"
+		cp bin/functions "${lib_dir}"/
 
-# Install kernel postinst and postrm hooks
-for d in postinst.d postrm.d ; do
-	mkdir -p "${etc_dir}"/kernel/"${d}"
-	cp etc/kernel/"${d}"/* "${etc_dir}"/kernel/"${d}"/
-done
+		# Install config files
+		mkdir -p "${etc_dir}"/default/tryboot.d "${etc_dir}"/tryboot.d
+		cp etc/tryboot "${etc_dir}"/default/
+		cp etc/tryboot.d/* "${etc_dir}"/tryboot.d/
+
+		# Install kernel postinst and postrm hooks
+		for d in postinst.d postrm.d ; do
+			mkdir -p "${etc_dir}"/kernel/"${d}"
+			cp etc/kernel/"${d}"/* "${etc_dir}"/kernel/"${d}"/
+		done
+		;;
+
+	rpi-tryboot)
+		lib_dir="${dest_dir}"/usr/lib/rpi-tryboot
+
+		# Install firmware files
+		mkdir -p "${lib_dir}"/tryboot
+		cp buildd/initrd.img "${lib_dir}"/tryboot/
+		cp -r firmware/boot/firmware/* "${lib_dir}"/tryboot/
+		find "${lib_dir}"/tryboot -type f -exec chmod 644 {} +
+
+		# Install hook scripts
+		mkdir -p "${lib_dir}"/hooks/
+		cp hooks/* "${lib_dir}"/hooks/
+		;;
+
+	*)
+		echo "Invalid package name: ${pkg_name}" >&2
+		exit 1
+		;;
+esac
