Rename to pi-tryboot
Signed-off-by: Juerg Haefliger <juergh@proton.me>

diff --git a/etc/kernel/postrm.d/zz-rpi-tryboot b/etc/kernel/postrm.d/zz-rpi-tryboot
--- a/etc/kernel/postrm.d/zz-rpi-tryboot
+++ b/etc/kernel/postrm.d/zz-rpi-tryboot
@@ -11,7 +11,7 @@ fi
 version=${1}
 
 if [ -z "${version}" ] ; then
-	echo "W: rpi-tryboot: Missing kernel version" >&2
+	echo "W: pi-tryboot: Missing kernel version" >&2
 	exit 2
 fi
 
